//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockMarket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol,Name,Sector
        ///MMM,3M,Industrials
        ///AOS,A. O. Smith,Industrials
        ///ABT,Abbott Laboratories,Health Care
        ///ABBV,AbbVie,Health Care
        ///ABMD,Abiomed,Health Care
        ///ACN,Accenture,Information Technology
        ///ATVI,Activision Blizzard,Communication Services
        ///ADM,ADM,Consumer Staples
        ///ADBE,Adobe,Information Technology
        ///AAP,Advance Auto Parts,Consumer Discretionary
        ///AMD,Advanced Micro Devices,Information Technology
        ///AES,AES Corp,Utilities
        ///AFL,Aflac,Financials
        ///A,Agilent Technologies,Health Care
        ///APD,Air Products &amp; Chemicals,Materials
        ///AKA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockNames {
            get {
                return ResourceManager.GetString("StockNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABT
        ///ABBV
        ///ABMD
        ///ACN
        ///ATVI
        ///ADBE
        ///AMD
        ///AAP
        ///AES
        ///AFL
        ///A
        ///APD
        ///AKAM
        ///ALK
        ///ALB
        ///ARE
        ///ALGN
        ///ALLE
        ///ALL
        ///AMZN
        ///AMCR
        ///AEE
        ///AAL
        ///AEP
        ///AXP
        ///AIG
        ///AMT
        ///AWK
        ///AMP
        ///ABC
        ///AME
        ///AMGN
        ///APH
        ///ADI
        ///ANSS
        ///ANTM
        ///AON
        ///AOS
        ///APA
        ///AAPL
        ///AMAT
        ///APTV
        ///ADM
        ///ANET
        ///AJG
        ///AIZ
        ///ATO
        ///ADSK
        ///ADP
        ///AZO
        ///AVB
        ///AVY
        ///AVGO
        ///BKR
        ///BLL
        ///BAC
        ///BBWI
        ///BAX
        ///BDX
        ///BRK.B
        ///BBY
        ///BIO
        ///BIIB
        ///BLK
        ///BK
        ///BA
        ///BKNG
        ///BWA
        ///BXP
        ///BSX
        ///BMY
        ///BR
        ///BRO
        ///BF.B
        ///BEN
        ///CHRW
        ///CDNS
        ///CZR
        ///CPB
        ///COF
        ///CAH
        ///CCL
        ///CARR
        ///CTLT
        ///CAT
        ///CBOE
        ///CBRE
        ///CDW
        ///CE
        ///CNC
        ///CNP
        ///CDAY
        ///CERN
        ///CF
        ///CRL
        ///CHTR
        ///CVX
        ///CMG
        ///CB
        ///CHD
        ///CI
        ///CINF
        ///CTAS
        ///CSCO
        ///C
        ///CFG
        ///CTXS
        ///CLX
        ///CME
        ///CMS
        ///CTSH
        ///CL
        ///CMCSA
        ///CMA
        ///CAG
        ///COP
        ///COO
        ///CPRT
        ///CTVA
        ///COST
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockNameSymbols {
            get {
                return ResourceManager.GetString("StockNameSymbols", resourceCulture);
            }
        }
    }
}
